### ISSUE TITLE
Error: arrayToHashSet is not a function

### ISSUE THREAD

**Issue by pingalit** [particle-iot/compile-action#21]
Hi,

First things first, really glad Particle worked on and implemented this! Thank you!

We're trying to implement CI/CD for our particle project.
First step: tried implemented the particle compile using this action.

Error:
```
Run particle-iot/compile-action@v1
  with:
    particle-platform-name: p1
    device-os-version: 3.3.1
    particle-access-token: ***
    auto-version: false
    auto-version-macro-name: PRODUCT_VERSION
    sources-folder: .
  
Auto-versioning is disabled, only doing version check
Could not find current product version macro, firmware-verion output will be undefined.
Access token provided, running cloud compilation
Compiling code in '.' for platform 'p1' with target version '3.3.1'
Error: arrayToHashSet is not a function
```

Here's the yaml file contents:
```yaml

particle-compile:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
            - name: Particle Compile
              id: compile
              uses: particle-iot/compile-action@v1
              with:
                particle-platform-name: 'p1'
                device-os-version: '3.3.1'
                particle-access-token: ${{ secrets.PARTICLE_CLOUD_SECRET }}
                auto-version: 'false'
                auto-version-macro-name: 'PRODUCT_VERSION'

```

I'm not sure why/what I can do to not get this error.
TIA!
